apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  namespace: metacoding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-server
          image: metacoding/frontend:3
          ports:
            - containerPort: 80
