apiVersion: v1
kind: Secret
metadata:
  name: user-secret
  namespace: metacoding
stringData:
  DB_USERNAME: metacoding
  DB_PASSWORD: metacoding1234
  JWT_SECRET: mySecretKeyForJWTTokenGenerationThatShouldBeAtLeast256BitsLongForHS256Algorithm
  JWT_EXPIRATION: "86400000"